# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/PYNQ-data/PYNQ-Z1_C.xdc

# IP: ip/dds_compiler_0/dds_compiler_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dds_compiler_0 || ORIG_REF_NAME==dds_compiler_0} -quiet] -quiet
