# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Matt/Documents/Vivado_Projects/MYIR_constraints.xdc

# IP: c:/Users/Matt/Documents/Vivado_Projects/ip_repo/dds_compiler_0_3/dds_compiler_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dds_compiler_0 || ORIG_REF_NAME==dds_compiler_0} -quiet] -quiet
