# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/PYNQ-data/PYNQ-Z1_C.xdc

# IP: ip/dds_compiler_0/dds_compiler_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_0 || ORIG_REF_NAME==dds_compiler_0} -quiet] -quiet

# Block Designs: bd/blk_diag1/blk_diag1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_diag1 || ORIG_REF_NAME==blk_diag1} -quiet] -quiet

# IP: bd/blk_diag1/ip/blk_diag1_audio_mixer_0_0/blk_diag1_audio_mixer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_diag1_audio_mixer_0_0 || ORIG_REF_NAME==blk_diag1_audio_mixer_0_0} -quiet] -quiet

# IP: bd/blk_diag1/ip/blk_diag1_clock_divider_0_0/blk_diag1_clock_divider_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_diag1_clock_divider_0_0 || ORIG_REF_NAME==blk_diag1_clock_divider_0_0} -quiet] -quiet

# IP: bd/blk_diag1/ip/blk_diag1_clock_divider_0_1/blk_diag1_clock_divider_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_diag1_clock_divider_0_1 || ORIG_REF_NAME==blk_diag1_clock_divider_0_1} -quiet] -quiet

# IP: bd/blk_diag1/ip/blk_diag1_midi_receiver_0_0/blk_diag1_midi_receiver_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_diag1_midi_receiver_0_0 || ORIG_REF_NAME==blk_diag1_midi_receiver_0_0} -quiet] -quiet

# IP: bd/blk_diag1/ip/blk_diag1_param_file_0_0/blk_diag1_param_file_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_diag1_param_file_0_0 || ORIG_REF_NAME==blk_diag1_param_file_0_0} -quiet] -quiet

# IP: bd/blk_diag1/ip/blk_diag1_i2s_transmit1_0_0/blk_diag1_i2s_transmit1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_diag1_i2s_transmit1_0_0 || ORIG_REF_NAME==blk_diag1_i2s_transmit1_0_0} -quiet] -quiet

# IP: bd/blk_diag1/ip/blk_diag1_clock_divider_2_0/blk_diag1_clock_divider_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_diag1_clock_divider_2_0 || ORIG_REF_NAME==blk_diag1_clock_divider_2_0} -quiet] -quiet

# IP: bd/blk_diag1/ip/blk_diag1_clock_divider_2_1/blk_diag1_clock_divider_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_diag1_clock_divider_2_1 || ORIG_REF_NAME==blk_diag1_clock_divider_2_1} -quiet] -quiet

# IP: bd/blk_diag1/ip/blk_diag1_i2s_transmit1_0_1/blk_diag1_i2s_transmit1_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_diag1_i2s_transmit1_0_1 || ORIG_REF_NAME==blk_diag1_i2s_transmit1_0_1} -quiet] -quiet

# IP: bd/blk_diag1/ip/blk_diag1_i2s_transmit1_0_2/blk_diag1_i2s_transmit1_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_diag1_i2s_transmit1_0_2 || ORIG_REF_NAME==blk_diag1_i2s_transmit1_0_2} -quiet] -quiet

# IP: bd/blk_diag1/ip/blk_diag1_clock_divider_2_2/blk_diag1_clock_divider_2_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_diag1_clock_divider_2_2 || ORIG_REF_NAME==blk_diag1_clock_divider_2_2} -quiet] -quiet

# IP: bd/blk_diag1/ip/blk_diag1_axi_uart16550_0_0/blk_diag1_axi_uart16550_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_diag1_axi_uart16550_0_0 || ORIG_REF_NAME==blk_diag1_axi_uart16550_0_0} -quiet] -quiet

# IP: bd/blk_diag1/ip/blk_diag1_processing_system7_0_0/blk_diag1_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_diag1_processing_system7_0_0 || ORIG_REF_NAME==blk_diag1_processing_system7_0_0} -quiet] -quiet

# IP: bd/blk_diag1/ip/blk_diag1_ps7_0_axi_periph_0/blk_diag1_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_diag1_ps7_0_axi_periph_0 || ORIG_REF_NAME==blk_diag1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/blk_diag1/ip/blk_diag1_rst_ps7_0_50M_0/blk_diag1_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_diag1_rst_ps7_0_50M_0 || ORIG_REF_NAME==blk_diag1_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/blk_diag1/ip/blk_diag1_util_vector_logic_0_0/blk_diag1_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_diag1_util_vector_logic_0_0 || ORIG_REF_NAME==blk_diag1_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/blk_diag1/ip/blk_diag1_xlconcat_0_0/blk_diag1_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_diag1_xlconcat_0_0 || ORIG_REF_NAME==blk_diag1_xlconcat_0_0} -quiet] -quiet

# IP: bd/blk_diag1/ip/blk_diag1_oscillator_0_0/blk_diag1_oscillator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_diag1_oscillator_0_0 || ORIG_REF_NAME==blk_diag1_oscillator_0_0} -quiet] -quiet

# IP: ip/dds_compiler_0/dds_compiler_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_0 || ORIG_REF_NAME==dds_compiler_0} -quiet] -quiet

# IP: bd/blk_diag1/ip/blk_diag1_xlconstant_0_0/blk_diag1_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_diag1_xlconstant_0_0 || ORIG_REF_NAME==blk_diag1_xlconstant_0_0} -quiet] -quiet

# IP: bd/blk_diag1/ip/blk_diag1_auto_pc_0/blk_diag1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_diag1_auto_pc_0 || ORIG_REF_NAME==blk_diag1_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/Matt/Documents/Vivado_Projects/fpga_synth/fpga_synth.gen/sources_1/bd/blk_diag1/blk_diag1_ooc.xdc
