set_property SRC_FILE_INFO {cfile:C:/Users/Matt/Documents/Vivado_Projects/fpga_synth/fpga_synth.srcs/constrs_1/imports/PYNQ-data/PYNQ-Z1_C.xdc rfile:../../../fpga_synth.srcs/constrs_1/imports/PYNQ-data/PYNQ-Z1_C.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN M20   IOSTANDARD LVCMOS33 } [get_ports { voice_enable_0[0] }]; #IO_L7N_T1_AD2N_35 Sch=sw[0]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN M19   IOSTANDARD LVCMOS33 } [get_ports { voice_enable_0[1] }]; #IO_L7P_T1_AD2P_35 Sch=sw[1]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D19   IOSTANDARD LVCMOS33 } [get_ports { clear_params }]; #IO_L4P_T0_35 Sch=btn[0]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN T14   IOSTANDARD LVCMOS33 } [get_ports { sck_osc }]; #IO_L5P_T0_34 Sch=ck_io[0]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN U12   IOSTANDARD LVCMOS33 } [get_ports { bck_osc }]; #IO_L2N_T0_34 Sch=ck_io[1]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN U13   IOSTANDARD LVCMOS33 } [get_ports { dout_osc }]; #IO_L3P_T0_DQS_PUDC_B_34 Sch=ck_io[2]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V13   IOSTANDARD LVCMOS33 } [get_ports { lrck_osc }]; #IO_L3N_T0_DQS_34 Sch=ck_io[3]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V17   IOSTANDARD LVCMOS33 } [get_ports { SerialIn_0 }]; #IO_L21P_T3_DQS_34 Sch=ck_io[8]
