# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Matt/Documents/Vivado_Projects/fpga_synth/fpga_synth.srcs/sources_1/bd/blk_diag1/ip/blk_diag1_processing_system7_0_0/blk_diag1_processing_system7_0_0.xci
# IP: The module: 'blk_diag1_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Matt/Documents/Vivado_Projects/fpga_synth/fpga_synth.gen/sources_1/bd/blk_diag1/ip/blk_diag1_processing_system7_0_0/blk_diag1_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_diag1_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/Matt/Documents/Vivado_Projects/fpga_synth/fpga_synth.srcs/sources_1/bd/blk_diag1/ip/blk_diag1_processing_system7_0_0/blk_diag1_processing_system7_0_0.xci
# IP: The module: 'blk_diag1_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Matt/Documents/Vivado_Projects/fpga_synth/fpga_synth.gen/sources_1/bd/blk_diag1/ip/blk_diag1_processing_system7_0_0/blk_diag1_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_diag1_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
